--  LAB 2 ACCESSING DATA PART 1
--  Put your answers on the lines after each letter. E.g. your query for question 1A should go on line 6; your query for question 1B should go on line 8...

--  1 
-- A 
SELECT * FROM EMPLOYEE;
-- B 
SELECT * FROM STOCK_ITEM;

--  2
-- A 
SELECT ITEM, PRICE FROM STOCK_ITEM;
-- B
SELECT FIRST_NAME, LAST_NAME, ROLE, PHONE FROM EMPLOYEE;

--  3
-- A
SELECT ITEM AS 'Product', CATEGORY AS 'Animal' FROM STOCK_ITEM;
-- B
SELECT LAST_NAME AS 'Pet Store Staff', EMPLOYEE_ID AS 'Emp. ID', SIN AS 'SIN' FROM EMPLOYEE;

--  4
-- A
SELECT FIRST_NAME, PHONE FROM EMPLOYEE WHERE ROLE ='SALES';
-- B
SELECT STOCK_ITEM_ID ,ITEM, INVENTORY FROM STOCK_ITEM WHERE INVENTORY  <=12;

--  5
-- A
SELECT ITEM AS 'KITTY CAT', PRICE FROM STOCK_ITEM WHERE CATEGORY = 'FELINE';
-- B
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS 'Staff Member' FROM EMPLOYEE WHERE EMPLOYEE_ID = 115;
